Add a safety check and improve error handling.
Grokzen/redis-py-cluster pull request #430
Opened 2021-01-29 07:32 UTC by aajay

- To fix https://github.com/Grokzen/redis-py-cluster/issues/419
   add a safety check to ensure there is no stale data before using the
   connection for executing a command.

- Improve error handling to ensure on any error the connection is disconnected
  before getting released back to the pool.
    
- Set connection to None as on ClusterDownError, the connection pool is reset, so to avoid
  the dangling connection getting added back to the pool.

2021-02-01 08:35 UTC, Grokzen commented
@aajay Is this the same code that upstream redis-py uses for this ready check feature?

2021-02-01 09:51 UTC, aajay commented
> @aajay Is this the same code that upstream redis-py uses for this ready check feature?

Yes @Grokzen. Added _check_ready_to_send() similar to redis-py. Apart from this, also fixed two other issues as described in the PR.

2021-02-17 10:12 UTC, aajay commented
@Grokzen Can you please review this PR?

2021-02-17 14:53 UTC, AmitANetskope commented
> > @aajay Is this the same code that upstream redis-py uses for this ready check feature?
> 
> Yes @Grokzen. Added _check_ready_to_send() similar to redis-py. Apart from this, also fixed two other issues as described in the PR.

Reference to similar check added in redis-py library - https://github.com/andymccurdy/redis-py/blob/master/redis/connection.py#L1147

2021-02-25 16:50 UTC, ns-smundle commented
@Grokzen Would you be able to help us with this review ?

2021-03-06 10:54 UTC, Grokzen requested changes
@aajay I need some kind of steps to validate these changes as there is no added tests inside this PR so w/o that i need to have some way to trigger this manually so i can see what scenario and case that this fixes. w/o that i won't merge this as it is. You can/should also add some tests for this. If this is some kind of fix from upstream redis-py then please port down the tests as well if they have any related to this.

2021-04-17 09:58 UTC, Grokzen commented
@aajay I manually implemented this into the code base as i needed to put the check logic elsewhere to mimic the place where redis-py implements it so i added it to the same place and not in the client class

https://github.com/Grokzen/redis-py-cluster/commit/95fee797dac63501f2933c8a0b46d72dbc5250d9

2021-04-17 09:58 UTC, closed without merging